package controller

const (
	NOCAN_SYS_ANY                   = 0
	NOCAN_SYS_ADDRESS_REQUEST       = 1
	NOCAN_SYS_ADDRESS_CONFIGURE     = 2
	NOCAN_SYS_ADDRESS_CONFIGURE_ACK = 3
	NOCAN_SYS_ADDRESS_LOOKUP        = 4
	NOCAN_SYS_ADDRESS_LOOKUP_ACK    = 5
	NOCAN_SYS_NODE_BOOT_REQUEST     = 6
	NOCAN_SYS_NODE_BOOT_ACK         = 7
	NOCAN_SYS_NODE_PING             = 8
	NOCAN_SYS_NODE_PING_ACK         = 9

	NOCAN_SYS_TOPIC_REGISTER       = 10
	NOCAN_SYS_TOPIC_REGISTER_ACK   = 11
	NOCAN_SYS_TOPIC_UNREGISTER     = 12
	NOCAN_SYS_TOPIC_UNREGISTER_ACK = 13

	NOCAN_SYS_TOPIC_SUBSCRIBE   = 14
	NOCAN_SYS_TOPIC_UNSUBSCRIBE = 15
	NOCAN_SYS_TOPIC_LOOKUP      = 16
	NOCAN_SYS_TOPIC_LOOKUP_ACK  = 17

	NOCAN_SYS_BOOTLOADER_GET_SIGNATURE     = 18
	NOCAN_SYS_BOOTLOADER_GET_SIGNATURE_ACK = 19
	NOCAN_SYS_BOOTLOADER_SET_ADDRESS       = 20
	NOCAN_SYS_BOOTLOADER_SET_ADDRESS_ACK   = 21
	NOCAN_SYS_BOOTLOADER_WRITE             = 22
	NOCAN_SYS_BOOTLOADER_WRITE_ACK         = 23
	NOCAN_SYS_BOOTLOADER_READ              = 24
	NOCAN_SYS_BOOTLOADER_READ_ACK          = 25
	NOCAN_SYS_BOOTLOADER_LEAVE             = 26
	NOCAN_SYS_BOOTLOADER_LEAVE_ACK         = 27
)
